# Generated by Django 5.1.6 on 2025-04-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainDeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(blank=True, max_length=128, null=True)),
                ('card_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
