# Generated by Django 5.1.6 on 2025-04-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindeckcard',
            name='card_attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maindeckcard',
            name='card_class',
            field=models.CharField(choices=[('Neutral', 'Neutral'), ('Forestcraft', 'Forestcraft'), ('Swordcraft', 'Swordcraft'), ('Runecraft', 'Runecraft'), ('Dragoncraft', 'Dragoncraft'), ('Abysscraft', 'Abysscraft'), ('Havencraft', 'Havencraft')], default='Neutral', help_text='Craft', max_length=18),
        ),
        migrations.AddField(
            model_name='maindeckcard',
            name='card_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maindeckcard',
            name='card_defence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maindeckcard',
            name='card_traits',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='maindeckcard',
            name='card_type',
            field=models.CharField(choices=[('Follower', 'Follower'), ('Amulet', 'Amulet'), ('Spell', 'Spell')], default='Follower', max_length=18),
        ),
        migrations.AddField(
            model_name='maindeckcard',
            name='set_number',
            field=models.CharField(default='BP01-001EN', max_length=18),
        ),
    ]
